admin_side/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from admin_side import views



app_name = 'admin_side'

urlpatterns = [
    path('logout/', views.logout_handler, name='logout'),
    path('', views.admin_login_handler, name='admin_login_handler'),
    path('admin_dashboard/', views.admin_dash_handler, name='admin_dash_handler'),
    path('admin_customer/', views.admin_user_handler, name='admin_user_manage'),
    path('customer_status/<int:user_id>', views.customer_status, name='customer_status'),
    path('customer-search/', views.customer_search, name='customer_search'),
    path('attribute-search/', views.attribute_search, name='attribute_search'),
    path('variant-search/', views.variant_search, name='variant_search'),
    path('product-search/', views.product_search, name='product_search'),
    path('category-search/', views.category_search, name='category_search'),
    path('brand-search/', views.brand_search, name='brand_search'),
    path('coupon-search/', views.coupon_search, name='coupon_search'),
    ]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authenticator/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

app_name = 'authentication'

urlpatterns = [
    path('otp-verify/', views.otp_verify, name='otp_verify'),
    path('login/', views.login_handler, name='login_handler'),
    path('logout/', views.logout_handler, name='logout'),
    path('sign/', views.sign_handler, name='sign_handler'),
    
    # Password reset views
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

# Static and media URLs
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from cart import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name='cart'

urlpatterns = [
    path('coupon-add',views.add_coupon,name='add_coupon'),
    path('coupon-delete/<int:id>/',views.delete_coupon,name='delete_coupon'),
    path('coupon-status/<int:id>/',views.status_coupon,name='status_coupon'),
    path('coupon-view',views.view_coupon,name='view_coupon'),
    path('cart-view',views.view_cart,name='view_cart'),
    path('cart-add/<int:id>/',views.add_cart,name='add_cart'),
    path('cart-add/',views.add_cart,name='add_cart'),
    path('cart-delete/<int:id>/',views.delete_cart,name='delete_cart'),
    path('plus-item/',views.item_plus,name='plus_item'),
    path('minus-item/',views.item_minus,name='minus_item'),
    path('remove-coupon/',views.remove_coupon,name='remove_coupon'),
    path('clear_cart/',views.clear_cart,name='clear_cart'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

seamless/urls.py
from django.contrib import admin
from django.urls import path,include
from social_django.views import auth, complete
from django.conf.urls.static import static
from seamless import settings



urlpatterns = [
    path('admin-orginal/', admin.site.urls), # for  Default django admin page

   path('', include('authenticator.urls')),    # for login sign up  management

   path('', include('user_side.urls')), # for client side works management

   path('my_admin/', include('admin_side.urls')), # for admin side works management

   path('cata/', include('category_manage.urls')),  # for catagory management

   path('pro/', include('products.urls')),  # for product management

   path('brand/', include('brands.urls')), # for brands management

    path('auth/', include('social_django.urls', namespace='social')),
    path('auth/', auth, name='social-auth'),
    path('auth/complete/google-oauth2/', complete, name='google-oauth2-complete'),

    path('cart-management/', include('cart.urls')), # for cart management

    path('account-management/', include('account.urls')), # for cart management

    path('order-management/', include('order_management.urls')), # for ordering and other stuffs


    path('wallet-management/', include('wallet.urls')), # for wallet management and other stuffsreview

    path('review_management_review_management/', include('review_management.urls')), # for wallet management and other stuffsreview



]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

user_side/urls.py
from django.urls import path
from seamless import settings
from user_side import views
from django.conf.urls.static import static

app_name = 'user_side'

urlpatterns = [

    path('', views.landing_handler, name='landing'),
    path('product-details/<int:id>', views.product_details, name='product_details'),
    path('add-to-wishlist/<int:id>/', views.add_wishlist, name='add_wishlist'),
    path('view-from-wishlist/', views.view_wishlist, name='view_wishlist'),
    path('delete-from-wishlist/<int:id>/', views.delete_wishlist, name='delete_wishlist'),
    path('product-list-here/' , views.product_list, name='product_list'),
    path('product-list-here/<int:id>' , views.product_list, name='product_list'),
    path('product-order-by-here/<str:order_by>' , views.product_sort, name='product_sort'),
    path('product_filter' , views.product_filter, name='product_filter'),
    path('view-all-category' , views.category_page, name='category_page'),
    path('all_search' , views.all_search, name='all_search'),
    path('search' , views.search, name='search'),


    path('change_profile_image/' , views.change_profile_image, name='change_profile_image'),
    

    



    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

templates/authentication/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>LOGIN PAGE</title>
  {% load static %}
  <link rel="shortcut icon" href="{% static 'imgs/favicon.png' %}"type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{% static 'css/authentication/login.css' %}">

</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="card">
          <form  class="box" method="POST" action="" >
  
            {% csrf_token %}
  
            {% for message in messages  %}
            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
              <strong>{{message}}</strong>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            <h1>Login</h1>
            <input type="text" name="log_id" placeholder="USERNAME OR EMAIL" />
            <input type="password" name="password" placeholder="PASSWORD" />
            {% comment %} <a class="forgot text-muted" href="{% url "authentication:password_reset" %}" ID='FORGOT'  style="color:black;" >FORGOT PASSWORD?</a> {% endcomment %}
            <input type="submit" name="" value="LOGIN" href="#" />
            <div class="col-md-12">

              <hr>
              
              <ul class="social-network social-circle">
                <li>
                  <a href="{% url 'social:begin' 'google-oauth2' %}" class="icoGoogle" title="Google +"
                    ><i class="fa-brands fa-google"><svg class="fa-brands fa-google" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="45" height="45" viewBox="0 0 48 48">
                      <path fill="#FFC107" d="M43.611,20.083H42V20H24v8h11.303c-1.649,4.657-6.08,8-11.303,8c-6.627,0-12-5.373-12-12c0-6.627,5.373-12,12-12c3.059,0,5.842,1.154,7.961,3.039l5.657-5.657C34.046,6.053,29.268,4,24,4C12.955,4,4,12.955,4,24c0,11.045,8.955,20,20,20c11.045,0,20-8.955,20-20C44,22.659,43.862,21.35,43.611,20.083z"></path><path fill="#FF3D00" d="M6.306,14.691l6.571,4.819C14.655,15.108,18.961,12,24,12c3.059,0,5.842,1.154,7.961,3.039l5.657-5.657C34.046,6.053,29.268,4,24,4C16.318,4,9.656,8.337,6.306,14.691z"></path><path fill="#4CAF50" d="M24,44c5.166,0,9.86-1.977,13.409-5.192l-6.19-5.238C29.211,35.091,26.715,36,24,36c-5.202,0-9.619-3.317-11.283-7.946l-6.522,5.025C9.505,39.556,16.227,44,24,44z"></path><path fill="#1976D2" d="M43.611,20.083H42V20H24v8h11.303c-0.792,2.237-2.231,4.166-4.087,5.571c0.001-0.001,0.002-0.001,0.003-0.002l6.19,5.238C36.971,39.205,44,34,44,24C44,22.659,43.862,21.35,43.611,20.083z"></path>
                      </svg></i></a>
                </li>
              </ul>
            </div>
            <a class="forgot " style="color:black;" href="{% url "authentication:sign_handler" %}" ID='FORGOT' >NEW TO SEAMLESS LIFE? SIGN UP</a>
            <br>
            <br>
            <br>
            <br>
             <a value="SKIP LOGIN"  style="color:black;" ID='FORGOT'  href="{% url "user_side:landing" %}" >SKIP LOGIN</a>
          </form>
          <a value="SKIP LOGIN"  style="color:black;" ID='FORGOT'  href="{% url "admin_side:admin_login_handler" %}">ADMIN LOGIN</a>
        </div>
      </div>
      
    </div>
  </div>
  
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"
  ></script>
</body>
</html>