cart/urls.py
from cart import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name='cart'

urlpatterns = [
    path('coupon-add',views.add_coupon,name='add_coupon'),
    path('coupon-delete/<int:id>/',views.delete_coupon,name='delete_coupon'),
    path('coupon-status/<int:id>/',views.status_coupon,name='status_coupon'),
    path('coupon-view',views.view_coupon,name='view_coupon'),
    path('cart-view',views.view_cart,name='view_cart'),
    path('cart-add/<int:id>/',views.add_cart,name='add_cart'),
    path('cart-add/',views.add_cart,name='add_cart'),
    path('cart-delete/<int:id>/',views.delete_cart,name='delete_cart'),
    path('plus-item/',views.item_plus,name='plus_item'),
    path('minus-item/',views.item_minus,name='minus_item'),
    path('remove-coupon/',views.remove_coupon,name='remove_coupon'),
    path('clear_cart/',views.clear_cart,name='clear_cart'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

review_management/urls.py
from django.urls import path
from review_management import views



app_name = 'review'

urlpatterns = [
    path('review_view/<int:id>', views.review_view, name = 'review_view'),
    path('add_review_view', views.add_review_view, name = 'add_review_view'),
]

seamless/urls.py
from django.contrib import admin
from django.urls import path,include
from social_django.views import auth, complete
from django.conf.urls.static import static
from seamless import settings



urlpatterns = [
    path('admin-orginal/', admin.site.urls), # for  Default django admin page

   path('', include('authenticator.urls')),    # for login sign up  management

   path('', include('user_side.urls')), # for client side works management

   path('my_admin/', include('admin_side.urls')), # for admin side works management

   path('cata/', include('category_manage.urls')),  # for catagory management

   path('pro/', include('products.urls')),  # for product management

   path('brand/', include('brands.urls')), # for brands management

    path('auth/', include('social_django.urls', namespace='social')),
    path('auth/', auth, name='social-auth'),
    path('auth/complete/google-oauth2/', complete, name='google-oauth2-complete'),

    path('cart-management/', include('cart.urls')), # for cart management

    path('account-management/', include('account.urls')), # for cart management

    path('order-management/', include('order_management.urls')), # for ordering and other stuffs


    path('wallet-management/', include('wallet.urls')), # for wallet management and other stuffsreview

    path('review_management_review_management/', include('review_management.urls')), # for wallet management and other stuffsreview



]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

user_side/urls.py
from django.urls import path
from seamless import settings
from user_side import views
from django.conf.urls.static import static

app_name = 'user_side'

urlpatterns = [

    path('', views.landing_handler, name='landing'),
    path('product-details/<int:id>', views.product_details, name='product_details'),
    path('add-to-wishlist/<int:id>/', views.add_wishlist, name='add_wishlist'),
    path('view-from-wishlist/', views.view_wishlist, name='view_wishlist'),
    path('delete-from-wishlist/<int:id>/', views.delete_wishlist, name='delete_wishlist'),
    path('product-list-here/' , views.product_list, name='product_list'),
    path('product-list-here/<int:id>' , views.product_list, name='product_list'),
    path('product-order-by-here/<str:order_by>' , views.product_sort, name='product_sort'),
    path('product_filter' , views.product_filter, name='product_filter'),
    path('view-all-category' , views.category_page, name='category_page'),
    path('all_search' , views.all_search, name='all_search'),
    path('search' , views.search, name='search'),


    path('change_profile_image/' , views.change_profile_image, name='change_profile_image'),
    

    



    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

cart/models.py
from django.db import models
from user_side.models import NewUser
from products.models import ProductVariant

class Coupon(models.Model):
    code = models.CharField(max_length=10, unique=True)
    discount = models.DecimalField(decimal_places=2, max_digits=8)
    valid_from = models.DateTimeField(auto_now_add=True)
    valid_to = models.DateTimeField()
    is_active = models.BooleanField(default= True)

    def __str__(self):
        return f"{self.code}- RS {self.discount}"
    
    def coupon_name (self):
        return f"{self.code}- RS {self.discount}"
    
class Cart(models.Model):
    user = models.ForeignKey(NewUser, on_delete=models.CASCADE)
    coupon = models.ForeignKey(Coupon, on_delete=models.CASCADE, null=True,blank=True)
    total = models.DecimalField(decimal_places=2, max_digits=10,default=0, null=True)
    sub_total = models.DecimalField(decimal_places=2, max_digits=10,default=0, null=True)
    shipping = models.DecimalField(decimal_places=2, max_digits=10,default=0, null=True)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user}-cart'



class Cart_Item(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(ProductVariant, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default= 1)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.cart}-item - {self.product}"
    
    

    

cart/forms.py
from django import forms
from django.forms import ModelForm
from .models import Coupon

class CouponForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name,field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = 'Enter here'
        self.fields['is_active'].widget.attrs['class'] = ''
        

    class Meta:
        model = Coupon
        fields = '__all__'
    valid_to = forms.DateTimeField(
        widget=forms.TextInput(attrs={'type': 'datetime-local'}),
    )

cart/views.py
from datetime import datetime as dt
from django.shortcuts import  get_object_or_404, render, redirect
from django.views.decorators.cache import cache_control
from django.contrib import messages
from cart.models import Coupon,Cart_Item,Cart
from django.db.models import Q
from cart.forms import CouponForm
from products.models import ProductVariant
from user_side.models import Wishlist
from decimal import Decimal
from django.http import JsonResponse
def add_coupon(request):
    if not request.user.is_authenticated:
        if not request.user.is_superuser:
            return redirect('admin_side:admin_login_handler')
        return redirect('user_side:landing')
    form = CouponForm()
    if request.method == "POST":
        form = CouponForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "the coupon has been created")
            return redirect("cart:add_coupon")
        else:   
            messages.warning(request,"the date format is not valid or the form is not valid")
    else:
        form = CouponForm()
    return render (request, 'admin/dashboard/cart/coupon.html',{'form':form})


def view_coupon(request):
    if not request.user.is_authenticated:
        if not request.user.is_superuser:
            return redirect('admin_side:admin_login_handler')
        return redirect('user_side:landing')
    time = dt.now()
    coup = Coupon.objects.filter(valid_to__lt = time)
    for coupon in coup:
        coupon.is_active = False
        coupon.save()
    print(coupon.is_active)


    coup = Coupon.objects.filter(valid_to__exact= dt.now())
    coup.delete()
    context={
        'coupon' : Coupon.objects.all(),
    }

    return render(request, 'admin/dashboard/cart/view_coupon.html',context)

def status_coupon(request,id):
    if not request.user.is_authenticated:
        if not request.user.is_superuser:
            return redirect('admin_side:admin_login_handler')
        return redirect('user_side:landing')
    if request.method=="POST":
        coupon = Coupon.objects.get(id = id)
        print(coupon)
        if coupon.is_active == True:
            coupon.is_active = False
            coupon.save()
            messages.info(request,f"the coupon {coupon} is set to INACTIVE")
        else:
            coupon.is_active = True
            coupon.save()
            messages.info(request,f"the coupon {coupon} is set to ACTIVE")

    return redirect('cart:view_coupon')


def delete_coupon(request, id):
    if not request.user.is_authenticated:
        if not request.user.is_superuser:
            return redirect('admin_side:admin_login_handler')
        return redirect('user_side:landing')
    if request.method == "POST":
        try:
            coupon = Coupon.objects.get(id=id)
            coupon.delete()
            messages.info(request,f'The coupon has been deleted {coupon}')
        except:
            pass
    return redirect('cart:view_coupon')



def view_cart(request):
    if not request.user.is_authenticated:
        if not request.user.is_superuser:
            return redirect('admin_side:admin_login_handler')
        return redirect('user_side:landing')

    cart, check_cart = Cart.objects.get_or_create(user=request.user)
    cart_items = Cart_Item.objects.filter(cart=cart).order_by('id')
    subtotal = sum(item.product.sale_price * item.quantity for item in cart_items)
    shipping = 0
    total = Decimal(subtotal)
    off = 0

    # checking if the user can get free delivery
    if subtotal < 200000:
        shipping = (subtotal * Decimal('0.1')) / 100
        total += shipping  # Include shipping in the total

        # Handle coupon application for the first time
    if request.method == 'POST':
        coupon_code = request.POST.get('user_coupon')
        code = Coupon.objects.filter(Q(is_active=True) & Q(code=coupon_code)).first()

        if code is None:
            messages.warning(request, f'{coupon_code} is an invalid Coupon Code')
        elif total != 0:
            cart.sub_total = subtotal
            cart.total = total - code.discount
            off = code.discount
            cart.coupon = code
            cart.shipping = shipping
            cart.save()
            messages.success(request,'the Coupon have been added to the cart')
            return redirect('cart:view_cart')

    # Check if the cart is empty and update the Cart model
    if not cart_items:
        cart.total = None
        cart.sub_total = None
        cart.coupon = None
        cart.shipping = None
        cart.save()
        messages.info(request,'Cart is Running on Low')
        
    context = {
        'item': cart_items,  # Renamed 'item' to 'items' for clarity
        'pro_subtotal': cart.sub_total if cart.sub_total else subtotal,
        'shipping': cart.shipping if cart.shipping else shipping,
        'total': cart.total if cart.total else total,
        'off': cart.coupon.discount if cart.coupon else off,
        'cart': Cart.objects.filter(user=request.user),
    }
    return render(request, 'user/cart.html', context)




def add_cart(request, id=None):
    if request.user.is_superuser:
        return JsonResponse({'error': 'User not authorized'}, status=403)

    product_quantity = int(request.POST.get('prod_qty')) if request.POST.get('prod_qty') else 1
    product_id = int(request.POST.get('prod_id')) if request.POST.get('prod_id') else id
    product = get_object_or_404(ProductVariant, id = product_id)
    cart, check_cart = Cart.objects.get_or_create(user=request.user)
    try:
        item_check = Cart_Item.objects.get(cart=cart, product=product)
    
        if product_quantity > product.stock :
            messages.warning(request, 'cant add that many due to stock insufficient')
            return redirect('cart:view_cart')
        elif item_check.quantity + product_quantity > product.stock:
             
            messages.warning(request, 'cant add that many due to stock insufficient')
            return redirect('cart:view_cart')
        else:
            
            item_check.quantity += product_quantity if product_quantity else 1
            item_check.save()
            cart_item = Cart_Item.objects.filter(cart = cart)
            subtotal = sum(item.product.sale_price * item.quantity for item in cart_item)
            coupon = cart.coupon
            shipping = 0
            if subtotal <200000:
                shipping = (subtotal * Decimal('0.1')) / 100
            cart.sub_total = subtotal
            cart.coupon = coupon
            subtotal -= coupon.discount if coupon else 0
            cart.total = subtotal if subtotal else 0
            cart.total += shipping if shipping else 0
            cart.shipping = shipping if shipping else 0
            cart.save()
            messages.success(request, 'The product is in the cart')
            return redirect("cart:view_cart")
    except Cart_Item.DoesNotExist:
        Cart_Item.objects.create(cart=cart, product=product, quantity=product_quantity if product_quantity else 1)
        cart_item = Cart_Item.objects.filter(cart = cart)
        subtotal = sum(item.product.sale_price * item.quantity for item in cart_item)
        coupon = cart.coupon
        shipping = 0
        if subtotal <200000:
            shipping = (subtotal * Decimal('0.1')) / 100
        cart.sub_total = subtotal
        cart.coupon = coupon
        subtotal -= coupon.discount if coupon else 0
        cart.total = subtotal if subtotal else 0
        cart.total += shipping if shipping else 0
        cart.shipping = shipping if shipping else 0
        cart.save()
        messages.success(request, 'The item has been added to the cart')
        wish = Wishlist.objects.filter(Q(my_user=request.user) & Q(wish_item=product))
        if wish:
            wish.delete()

        return redirect("cart:view_cart")





def delete_cart(request,id):
    cart_item = Cart_Item.objects.filter(id = id)
    if cart_item:
        cart_item.delete()
        messages.info(request, f"the item has been deleted from cart")
    myCart =Cart.objects.get(user = request.user)
    del_cart = Cart_Item.objects.filter(cart =myCart)
    coupon = myCart.coupon
    subtotal = sum(item.product.sale_price * item.quantity for item in del_cart) 
    product_per_price = subtotal
    shipping = Decimal(0)
    if subtotal < 200000:
        shipping = (subtotal * Decimal('0.1'))/100
    subtotal -= coupon.discount if coupon else 0
    myCart.sub_total = product_per_price if product_per_price else 0
    myCart.total = subtotal
    myCart.total += shipping if shipping else 0
    myCart.shipping = shipping if shipping else 0
    myCart.save()
    if del_cart is None:
        myCart.total = None
        myCart.sub_total = None
        myCart.coupon = None
        myCart.shipping = None
    return redirect('cart:view_cart')

def item_plus(request):
   
    if request.headers.get('x-requested-with') == 'XMLHttpRequest' and request.method == 'POST':
        try:
            cart = get_object_or_404(Cart, user = request.user)
            id = request.POST.get('cart_id')
            cart_item = get_object_or_404(Cart_Item, cart = cart, id = id)
            if cart_item.quantity < cart_item.product.stock:
                cart_item.quantity += 1
                cart_item.save()
            subtotal = Decimal(0)   
            coupon = cart.coupon
            cart_item = Cart_Item.objects.filter(cart = cart)
            subtotal = sum(item.product.sale_price * item.quantity for item in cart_item) 
            product_per_price = subtotal
            shipping = Decimal(0)
            if subtotal < 200000:
                shipping = (subtotal * Decimal('0.1'))/100
        
            subtotal -= coupon.discount if coupon else 0
            cart.sub_total = product_per_price if product_per_price else 0
            cart.total = subtotal
            cart.total += shipping if shipping else 0
            cart.shipping = shipping if shipping else 0

templates/user/order_placed_view.html
{% extends "base.html" %} 
{% block title %}USER CHECKOUT PAGE{% endblock title %} 
{%block main %}
{% load static %} 

<link rel="stylesheet" href="{% static 'css/main.css' %}">




<div>
    <img style="margin-left:20%" width="60%" height="60%" src="{% static 'imgs/order placed.jpg' %}" alt="">
    <a href="{% url "user_side:landing" %}" ><button style="position:relative; bottom:22.3rem; right:44rem;  padding-right:70px; padding-left:70px; padding-top:20px; border-radius:25px" class="btn button" type="button">DONE</button></a>
</div>


{% endblock main %} 

templates/user/products_list.html
{% extends "base.html" %} 
{% block title %}PRODUCT LIST{% endblock title %} 
{%block main %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">


<main class="main">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="{% url "user_side:landing" %}" rel="nofollow">Home</a>
                <span></span> Shop
            </div>
        </div>
    </div>

    <section class="mt-50 mb-50">
        <div class="container">
            <div class="row flex-row-reverse">
                <div class="col-lg-9">
                    
                    {% comment %} recommendation will be shown here {% endcomment %}
                    <div class="row product-grid-3">
                        {% if recommend_products %}
                        <div class="shop-product-fillter">
                            <div class="totall-product">
                                <p><strong class="text-brand">Products You May Also like</strong></p>
                            </div>
                        </div>

                        {% for all in recommend_products %}
                        <div class="col-lg-4 col-md-4 col-12 col-sm-6" >
                            <div class="product-cart-wrap mb-30">
                                <div class="product-img-action-wrap">
                                    <div class="product-img product-img-zoom">
                                        <a href="{% url "user_side:product_details" id=all.id %}">
                                            <img class="default-img" width='90px'  height='230px' src="{{all.variantimage_set.first.images.url}}" alt="">
                                        </a>
                                    </div>
                                    <div class="product-action-1">
                                        {% if all.sale_price > 0 %}
                                        {% if user.is_authenticated %}
                                        <a aria-label="Love and View" class="action-btn hover-up" href="{% url "user_side:add_wishlist" id=all.id %}"><i class="fi-rs-heart"></i></a>
                                        {% endif %}
                                        {% endif %}
                                    </div>
                                    <div class="product-badges product-badges-position product-badges-mrg">
                                        <span class="hot">Hot</span>
                                    </div>
                                </div>
                                
                                <div class="product-content-wrap">
                                    <h2><a href="shop-product-right.html">{{ all.get_variant_name }}</a></h2>
                                    {% if all.sale_price > 0 %}
                                    <div class="rating-result" title="90%">
                                        <span>
                                            <span>90%</span>
                                        </span>
                                    </div>
                                    <div class="product-price">
                                        
                                        <span>{{all.sale_price}} </span>
                                        {% if  all.sale_price != all.max_price%}
                                        <span class="old-price">{{all.max_price}}</span>
                                        {% endif %}
                                    </div>
                                    {% if user.is_authenticated %}
                                    <div class="product-action-1 show">

                                        {% if all.stock < 1 %}
                                    <img width="40" height="40" src="https://img.icons8.com/external-victoruler-linear-colour-victoruler/64/external-out-of-stock-logistics-victoruler-linear-colour-victoruler.png" alt="external-out-of-stock-logistics-victoruler-linear-colour-victoruler"/>
                                    {% else %}      
                                    <a aria-label="Add To Cart" class="action-btn hover-up" href="{% url "cart:add_cart" id=all.id %}"><i class="fi-rs-shopping-bag-add"></i></a>
                                        {% endif %}
                                        
                                    </div>
                                    {% endif %}
                                    {% else %}
                                    <span  class="text-brand" style="padding-top:30px;">Currently Unavailable</span>
                                
                                    {% endif %}
                                </div>
                                
                            </div>
                        </div>
                        {% endfor %}
                        {% endif %}
                    </div>
                    

                    {% comment %} recommendation will end here {% endcomment %}
                    <div class="shop-product-fillter">
                        <div class="totall-product">
                            <p> We found <strong class="text-brand">{{total}}</strong> items for you!</p>
                        </div>
                    </div>
                    <div class="row product-grid-3">
                        {% for all in all_products %}
                        <div class="col-lg-4 col-md-4 col-12 col-sm-6" >
                            <div class="product-cart-wrap mb-30">
                                <div class="product-img-action-wrap">
                                    <div class="product-img product-img-zoom">
                                        <a href="{% url "user_side:product_details" id=all.id %}">
                                            <img class="default-img" width='90px'  height='230px' src="{{all.variantimage_set.first.images.url}}" alt="">
                                        </a>
                                    </div>
                                    <div class="product-action-1">
                                        {% if all.sale_price > 0 %}
                                        {% if user.is_authenticated %}
                                        <a aria-label="Love and View" class="action-btn hover-up" href="{% url "user_side:add_wishlist" id=all.id %}"><i class="fi-rs-heart"></i></a>
                                        {% endif %}
                                        {% endif %}
                                    </div>
                                    <div class="product-badges product-badges-position product-badges-mrg">
                                        <span class="hot">Hot</span>
                                    </div>
                                </div>
                                
                                <div class="product-content-wrap">
                                    <h2><a href="shop-product-right.html">{{ all.get_variant_name }}</a></h2>
                                    {% if all.sale_price > 0 %}
                                    <div class="rating-result" title="90%">
                                        <span>
                                            <span>90%</span>
                                        </span>
                                    </div>
                                    <div class="product-price">
                                        
                                        <span>{{all.sale_price}} </span>
                                        {% if  all.sale_price != all.max_price%}
                                        <span class="old-price">{{all.max_price}}</span>
                                        {% endif %}
                                    </div>
                                    {% if user.is_authenticated %}
                                    <div class="product-action-1 show">

                                        {% if all.stock < 1 %}
                                    <img width="40" height="40" src="https://img.icons8.com/external-victoruler-linear-colour-victoruler/64/external-out-of-stock-logistics-victoruler-linear-colour-victoruler.png" alt="external-out-of-stock-logistics-victoruler-linear-colour-victoruler"/>
                                    {% else %}      
                                    <a aria-label="Add To Cart" class="action-btn hover-up" href="{% url "cart:add_cart" id=all.id %}"><i class="fi-rs-shopping-bag-add"></i></a>
                                        {% endif %}
                                        
                                    </div>
                                    {% endif %}
                                    {% else %}
                                    <span  class="text-brand" style="padding-top:30px;">Currently Unavailable</span>
                                
                                    {% endif %}
                                </div>
                                
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <!--pagination-->
                    <div class="pagination-area mt-15 mb-sm-5 mb-lg-0">
                        <nav aria-label="Page navigation example">
                            <ul class="pagination justify-content-start">
                                <li class="page-item active"><a class="page-link" href="#">01</a></li>
                                <li class="page-item"><a class="page-link" href="#">02</a></li>
                                <li class="page-item"><a class="page-link" href="#">03</a></li>
                                <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                                <li class="page-item"><a class="page-link" href="#">16</a></li>
                                <li class="page-item"><a class="page-link" href="#"><i class="fi-rs-angle-double-small-right"></i></a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-3 primary-sidebar sticky-sidebar">
                    <div class="widget-category mb-30">
                        <h5 class="section-title style-1 mb-30 wow fadeIn animated">Category</h5>
                        <ul class="categories">
                            <li><a href="{% url "user_side:product_list"%}">ALL PRODUCTS</a></li>
                            {% for cat in category%}
                            <li><a href="{% url "user_side:product_list" id=cat.id%}">{{cat.category_name}}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <!-- Fillter By Price -->
                    <div class="sidebar-widget product-sidebar  mb-30 p-30 bg-grey border-radius-10">
                        <h5 class="section-title style-1 mb-30 wow fadeIn animated">FILTER BY PRICE</h5>
                        <form action="{% url "user_side:product_filter" %}" method="POST">
                            {% csrf_token %}
                            <div style="display:flex;">
                                <input type="number" name="min_price" id="min_price" class="form-action" style="margin-right:10px;" default="0">
                                <input type="number" name="max_price" id="max_price" class="form-action" default="0">
                            </div>
                            <button type="submit" class="btn button" style="margin-left:10px; margin-top:20px;">FILTER THE PRICE</button>
                        </form>
                    </div>
                    <!-- Product sidebar Widget -->
                    <div class="sidebar-widget product-sidebar  mb-30 p-30 bg-grey border-radius-10">
                        <div class="widget-category mb-30">
                            <h5 class="section-title style-1 mb-30 wow fadeIn animated">ORDER BY</h5>
                            <ul class="categories">
                                <li><a href="{% url "user_side:product_sort" order_by='sale_price' %}">LOW - HIGH</a></li>
                                <li><a href="{% url "user_side:product_sort" order_by='-sale_price' %}">HIGH - LOW</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>


{% endblock main %}